import { Badge } from './types';
import { formatDuration } from './utils/timeUtils';

export const BADGES: Badge[] = [
  { id: 'time-1', name: 'Explorer', description: 'Study for 1 hour.', icon: 'compass', type: 'time', value: 3600 },
  { id: 'time-2', name: 'Curious Learner', description: 'Study for 2 hours.', icon: 'magnifying-glass', type: 'time', value: 7200 },
  { id: 'time-3', name: 'Steady Starter', description: 'Study for 3 hours.', icon: 'notebook-pen', type: 'time', value: 10800 },
  { id: 'time-4', name: 'Focused Mind', description: 'Study for 5 hours.', icon: 'glowing-brain', type: 'time', value: 18000 },
  { id: 'time-5', name: 'Fast Grower', description: 'Study for 8 hours.', icon: 'sprout', type: 'time', value: 28800 },
  { id: 'time-6', name: 'Diligent Student', description: 'Study for 10 hours.', icon: 'open-book', type: 'time', value: 36000 },
  { id: 'time-7', name: 'Consistent Climber', description: 'Study for 15 hours.', icon: 'mountain-climber', type: 'time', value: 54000 },
  { id: 'time-8', name: 'Knowledge Seeker', description: 'Study for 20 hours.', icon: 'telescope', type: 'time', value: 72000 },
  { id: 'time-9', name: 'Determined Achiever', description: 'Study for 25 hours.', icon: 'gold-medal', type: 'time', value: 90000 },
  { id: 'time-10', name: 'Persistent Thinker', description: 'Study for 30 hours.', icon: 'light-bulb', type: 'time', value: 108000 },
  { id: 'time-11', name: 'Rising Scholar', description: 'Study for 35 hours.', icon: 'graduation-cap', type: 'time', value: 126000 },
  { id: 'time-12', name: 'Time Keeper', description: 'Study for 40 hours.', icon: 'hourglass', type: 'time', value: 144000 },
  { id: 'time-13', name: 'Calm Learner', description: 'Study for 45 hours.', icon: 'lotus-flower', type: 'time', value: 162000 },
  { id: 'time-14', name: 'Halfway Hero', description: 'Study for 50 hours.', icon: 'shield-sword', type: 'time', value: 180000 },
  { id: 'time-15', name: 'Smart Strategist', description: 'Study for 60 hours.', icon: 'chess-piece', type: 'time', value: 216000 },
  { id: 'time-16', name: 'Resilient Learner', description: 'Study for 70 hours.', icon: 'brick-wall', type: 'time', value: 252000 },
  { id: 'time-17', name: 'Deep Diver', description: 'Study for 80 hours.', icon: 'scuba-gear', type: 'time', value: 288000 },
  { id: 'time-18', name: 'Bright Mind', description: 'Study for 90 hours.', icon: 'shining-gem', type: 'time', value: 324000 },
  { id: 'time-19', name: 'Century Learner', description: 'Study for 100 hours.', icon: 'glowing-100', type: 'time', value: 360000 },
  { id: 'time-20', name: 'Insight Builder', description: 'Study for 120 hours.', icon: 'building-construction', type: 'time', value: 432000 },
  { id: 'time-21', name: 'Trail Finder', description: 'Study for 140 hours.', icon: 'footprints-trail', type: 'time', value: 504000 },
  { id: 'time-22', name: 'Mind Architect', description: 'Study for 160 hours.', icon: 'brain-blueprint', type: 'time', value: 576000 },
  { id: 'time-23', name: 'Focus Master', description: 'Study for 180 hours.', icon: 'target-arrow', type: 'time', value: 648000 },
  { id: 'time-24', name: 'Wise Builder', description: 'Study for 200 hours.', icon: 'puzzle-complete', type: 'time', value: 720000 },
  { id: 'time-25', name: 'Persistent Soul', description: 'Study for 220 hours.', icon: 'small-flame', type: 'time', value: 792000 },
  { id: 'time-26', name: 'Mind Voyager', description: 'Study for 240 hours.', icon: 'rocket-ship', type: 'time', value: 864000 },
  { id: 'time-27', name: 'Creative Thinker', description: 'Study for 260 hours.', icon: 'paint-palette', type: 'time', value: 936000 },
  { id: 'time-28', name: 'Time Investor', description: 'Study for 280 hours.', icon: 'gold-clock', type: 'time', value: 1008000 },
  { id: 'time-29', name: 'Knowledge Guardian', description: 'Study for 300 hours.', icon: 'book-shield', type: 'time', value: 1080000 },
  { id: 'time-30', name: 'Skill Sculptor', description: 'Study for 320 hours.', icon: 'sculpture-chisel', type: 'time', value: 1152000 },
  { id: 'time-31', name: 'Mind Warrior', description: 'Study for 340 hours.', icon: 'shining-sword', type: 'time', value: 1224000 },
  { id: 'time-32', name: 'Reflection Sage', description: 'Study for 360 hours.', icon: 'candle-book', type: 'time', value: 1296000 },
  { id: 'time-33', name: 'Knowledge Pilot', description: 'Study for 380 hours.', icon: 'paper-airplane', type: 'time', value: 1368000 },
  { id: 'time-34', name: 'Growth Keeper', description: 'Study for 400 hours.', icon: 'large-tree', type: 'time', value: 1440000 },
  { id: 'time-35', name: 'Journey Thinker', description: 'Study for 420 hours.', icon: 'railroad-tracks', type: 'time', value: 1512000 },
  { id: 'time-36', name: 'Dream Pursuer', description: 'Study for 440 hours.', icon: 'shooting-star', type: 'time', value: 1584000 },
  { id: 'time-37', name: 'Knowledge Innovator', description: 'Study for 460 hours.', icon: 'glowing-gears', type: 'time', value: 1656000 },
  { id: 'time-38', name: 'Mind Mentor', description: 'Study for 480 hours.', icon: 'chalkboard-book', type: 'time', value: 1728000 },
  { id: 'time-39', name: 'Half-Millennium Hero', description: 'Study for 500 hours.', icon: 'superhero-aura', type: 'time', value: 1800000 },
  { id: 'time-40', name: 'Time Sage', description: 'Study for 550 hours.', icon: 'antique-clock', type: 'time', value: 1980000 },
  { id: 'time-41', name: 'Great Scholar', description: 'Study for 600 hours.', icon: 'ancient-scroll', type: 'time', value: 2160000 },
  { id: 'time-42', name: 'Wisdom Keeper', description: 'Study for 700 hours.', icon: 'golden-key', type: 'time', value: 2520000 },
  { id: 'time-43', name: 'Knowledge Explorer', description: 'Study for 800 hours.', icon: 'ancient-compass', type: 'time', value: 2880000 },
  { id: 'time-44', name: 'Eternal Learner', description: 'Study for 900 hours.', icon: 'infinity-symbol', type: 'time', value: 3240000 },
  { id: 'time-45', name: 'Time Legend', description: 'Study for 1000 hours.', icon: 'clock-light-rays', type: 'time', value: 3600000 },
  { id: 'time-46', name: 'Master of Growth', description: 'Study for 1200 hours.', icon: 'golden-trophy', type: 'time', value: 4320000 },
  { id: 'time-47', name: 'Zen Learner', description: 'Study for 1500 hours.', icon: 'yin-yang', type: 'time', value: 5400000 },
  { id: 'time-48', name: 'Knowledge Guardian Elite', description: 'Study for 1800 hours.', icon: 'energy-orb', type: 'time', value: 6480000 },
  { id: 'time-49', name: 'Eternal Sage', description: 'Study for 2000 hours.', icon: 'glowing-quill', type: 'time', value: 7200000 },
  { id: 'time-50', name: 'Legend of Time', description: 'Study for 2500 hours.', icon: 'crystal-crown', type: 'time', value: 9000000 },
];
